# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170822_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_end_date',
            field=models.CharField(default='1/1/1', max_length=150),
            preserve_default=False,
        ),
    ]
