# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_product_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_end_date',
            field=models.DateTimeField(),
        ),
    ]
