# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20170823_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.CharField(max_length=500),
        ),
    ]
